company_id: aboutpet
model: carca
version: v1

embed_dim: 128
num_heads: 4
num_layers: 1
max_len: 50
dropout: 0

lr: 0.0001
weight_decay: 0.01

datamodule_batch_size: 256
datamodule_num_workers: 10
datamodule_negative_k: 10

encoder_residual_strategy_1: sum
encoder_residual_strategy_2: sum
decoder_residual_strategy_1: sum
decoder_residual_strategy_2: sum

trainer_max_epochs: 100
trainer_limit_val_batches: 1.0
trainer_limit_train_batches: 1.0
trainer_limit_test_batches: 1.0
trainer_strategy: "auto"  # deepspeed_stage_1
trainer_precision: "16-mixed"
trainer_profiler: "simple"

#checkpoint_dirpath: "/tmp/aboutpet/carca/v1/checkpoints"
checkpoint_monitor: "val_ndcg@10"
checkpoint_filename: "ndcg@10.max"
checkpoint_mode: "max"
checkpoint_every_n_train_steps: 10000
ckpt_path: "last"
