version: v1

embed_dim: 128  # 32
num_layers: 0

lr: 0.001
weight_decay: 0.01

datamodule_batch_size: 4096  # 2048
datamodule_num_workers: 10
datamodule_negative_k: 10

trainer_max_epochs: 3
trainer_limit_val_batches: 1.0
trainer_limit_train_batches: 1.0
trainer_limit_test_batches: 1.0
trainer_strategy: "auto"  # deepspeed_stage_1
trainer_precision: "16"
trainer_profiler: "simple"

checkpoint_dirpath: "/tmp/gsshop/item2vec/v1/checkpoints"
checkpoint_monitor: "train_loss"
checkpoint_filename: "{epoch}-{step}-{train_loss:.2f}"
checkpoint_mode: "min"
checkpoint_every_n_train_steps: 10000
ckpt_path: "last"
