embed_dim: 64
num_heads: 1
num_layers: 1
max_len: 50
dropout: 0.1

lr: 0.0001
weight_decay: 0.01

datamodule_batch_size: 256
datamodule_num_workers: 10
datamodule_negative_k: 10

trainer_max_epochs: 100
trainer_limit_val_batches: 1.0
trainer_limit_train_batches: 1.0
trainer_limit_test_batches: 1.0
trainer_strategy: "auto"  # deepspeed_stage_1
trainer_precision: "16"
trainer_profiler: "simple"

checkpoint_dirpath: "/tmp/gsshop/carca/v1/checkpoints"
checkpoint_monitor: "val_ndcg@10"
checkpoint_filename: "{epoch}-{step}-{train_loss:.2f}"
checkpoint_mode: "max"
checkpoint_every_n_train_steps: 10000
checkpoint_path: "last"

wandb_api_key: "7290cd5cb94c29300893438a08b4b6aa844149f3"
