company_id: wshop
model: item2vec
version: v1

# dataset
skipgram_window_size: 5
blacklist:
  - '65eb1d87-720d-49ab-8df5-7eaf7fd8b4ae'
  - 'fbc7a0dc-ae05-4933-aae9-84d9ea02cda9'
  - '4eb1d876-30d9-4ab0-bf56-faf7fd8b4aeb'
  - 'dfcab32b-cc6c-4c37-a299-ed725194e78c'
  - '1262294'

# train
embed_dim: 128  # 32
num_layers: 3

lr: 0.001
weight_decay: 0.01

datamodule_batch_size: 1024
datamodule_num_workers: 10
datamodule_negative_k: 10

trainer_max_epochs: 1
trainer_limit_val_batches: 1.0
trainer_limit_train_batches: 1.0
trainer_limit_test_batches: 1.0
trainer_strategy: "auto"  # deepspeed_stage_1
trainer_precision: "16-mixed"
trainer_profiler: "simple"

checkpoint_monitor: "val_graph_dot_ndcg@20"
checkpoint_filename: "{epoch}-{step}-{train_loss:.2f}"
checkpoint_mode: "max"
checkpoint_every_n_train_steps: 10000
ckpt_path: "last"
